Shade all com.google dependencies
This is a temporary workaround for tmc-netbeans where weird classloading
causes NoSuchMethodErrors. We can get rid of this fork when we're ready
to fully migrate to Java 8 and checkstyle no longer depends on Guava.